using System.Diagnostics;
using InventoryManager.Models;
using Microsoft.AspNetCore.Mvc;
/*
 * HomeController.cs:
 * ******************
 * The default controller generated by the ASP.NET Core MVC template.
 * It gives us a clear demonstration about implementing the following:
 *  - Controller classes
 *  - Action methods
 *  - Returning Razor Views
 *  - Constructor Dependency Injection
 */
namespace InventoryManager.Controllers
{
    public class HomeController : Controller
    {
        // Logger provided through ASP.NET Core's built-in Dependency Injection.
        private readonly ILogger<HomeController> _logger;

        // Constructor Injection.
        // ASP.NET Core automatically provides an ILogger<HomeController> instance.
        // ASP.NET Core injects the logger through the constructor.
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        // Displays the application's home page.
        public IActionResult Index()
        {
            return View();
        }

        
        // Displays the Privacy page (UNSED METHOD!):
        //public IActionResult Privacy()
        //{
        //    return View();
        //}

        // Displays the application's error page.
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    } // class
} // namespace
